compusoft/urls.py
#####################################################
#											   		#
#		CompuSoft - The Compushow 2017 Software	    #
#											   		#
#####################################################
#													#
#	- Main URL configuration file. Maps URLs to		#
#	  the voting app.								#
#													#
#####################################################

from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import url, include

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('voting.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

voting/urls.py
#####################################################
#                                                   #
#       CompuSoft - The Compushow 2017 Software     #
#                                                   #
#####################################################
#                                                   #
#  			   - URL configuration file.   			#
#                                                   #
#####################################################


from django.conf.urls import url

from . import views

app_name = 'voting'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^nominate/$', views.nominate, name='nominate'),
	url(r'^info/$', views.get_student_info, name='get_student_info'),
	url(r'^voteinfo/$', views.get_vote_info, name='get_vote_info'),
	url(r'^vote/$', views.vote, name='vote'),
	url(r'^voting/$', views.voting, name='voting'),
	url(r'^login/$', views.log_in, name='log_in'),
	url(r'^logout/$', views.log_out, name='log_out'),
	url(r'^delete_nomination/$', views.delete_nomination, name='delete_nomination'),
	url(r'^make_nomination/$', views.make_nomination, name='make_nomination'),
	url(r'^view_profile/$', views.view_profile, name='view_profile'),
	url(r'^pswd/$', views.upd_pswd, name='upd_pswd'),
	url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
	url(r'^categories/$', views.categories, name='categories'),
	url(r'^category/$', views.category, name='category'),
	url(r'^voting_from_bot/$', views.voting_from_bot, name='voting_from_bot'),
	url(r'^login_bot/$', views.login_bot, name='login_bot')
]

voting/forms.py
#####################################################
#                                                   #
#       CompuSoft - The Compushow 2017 Software     #
#                                                   #
#####################################################
#                                                   #
#  	  				Forms file.  					#
#                                                   #
#####################################################

from django import forms
from django.core.validators import RegexValidator

class LoginForm(forms.Form):
	student_id = forms.CharField(
		label = "ID",
		strip = True,
		validators = [RegexValidator(
			regex = '^([0-9]){2}-([0-9]){5}$',
			message = "Invalid ID e.g. 00-12345")],
	)

	password = forms.CharField(
		label = "Password",
		widget = forms.PasswordInput,
	)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['student_id'].widget.attrs.update({
			'id': 'inputID',
			'class': 'form-control',
			'placeholder': 'Carnet: xx-xxxxx',
			'autofocus': True,
			'required': True
		})
		self.fields['password'].widget.attrs.update({
			'id': 'inputPassword',
			'class': 'form-control',
			'placeholder': 'Contraseña: cédula',
			'required': True
		})

voting/views.py
#####################################################
#                                                   #
#       CompuSoft - The Compushow 2017 Software     #
#                                                   #
#####################################################
#                                                   #
#  	  		 - Views file of the CompuSoft.  		#
#                                                   #
#####################################################

import json
from functools import reduce
from random import shuffle, randint
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User, update_last_login
from django.core.mail import EmailMessage

from pprint import pprint
from .forms import LoginForm
from .library import *

from .models import *
from django.core import serializers

from django.views.decorators.csrf import csrf_exempt

from django.core.exceptions import ObjectDoesNotExist

import os
TOKEN_BOT = os.environ.get('TOKEN_BOT')
##############################################
# Flag to enable voting modules (important!) #
##############################################
enable_voting = True                        #
##############################################

@login_required()
def index(request):
    students = get_students()
    return render(request, 'voting/index.html', {
        'home':True,
        'students':students,
        'enable_voting':enable_voting,
        'safari': browser_safari(request.META['HTTP_USER_AGENT'])
    })

def log_in(request):

    # Redirect if user already logged in
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    if request.method == 'POST':

        if request.user.is_authenticated():
            return HttpResponseRedirect('/')

        form = LoginForm(request.POST)
        if form.is_valid():
            student_id = form.cleaned_data['student_id']
            password = form.cleaned_data['password']
            print(student_id)
            print(password)

            if not user_is_registered(student_id):
                print(student_id)
                print(password)
                result = validate_and_register_user(student_id)
                if result == 'id not found':
                    # student id not found in ldap
                    return render(request, 'voting/login.html', {'form':form, 'invalid':True, 'notfound':True})
                    
                elif result == 'not computer science student':
                    return render(request, 'voting/login.html', {'form':form, 'invalid':True, 'notcs':True})					
            print('aqui')
            user = authenticate(username=student_id, password=password)

            if user is not None:

                if account_activated(user):
                    login(request, user)
                    request.session['profileimage'] = '/voting/images/profilePhotos/' + get_user_image(user) + '.jpg'
                else:
                    account_activation_email(request, user)
                    return render(request, 'voting/login.html', {'form':form, 'not_activated':True})

                return HttpResponseRedirect('/')
            
            else:
                return render(request, 'voting/login.html', {'form':form, 'invalid':True, 'invalidpasswd':True})

        else:
            return render(request, 'voting/login.html', {'form':form})

    else:
        form = LoginForm()
        return render(request, 'voting/login.html', {'form':form})

@login_required()
def nominate(request):

    categories  = get_categories()
    students    = get_students()
    nominations, categories_exist = get_nominations(request.user)
    categories = [categories[0:6], categories[6:12], categories[12:]]
    return render(request, 'voting/nominate.html', {
        'nominate':True,
        'categories':categories,
        'students':students,
        'nominations':nominations,
        'categories_exist':categories_exist,
        'enable_voting':enable_voting,
        'safari': browser_safari(request.META['HTTP_USER_AGENT'])
    })

@login_required()
def log_out(request):
    logout(request)
    return HttpResponseRedirect('/login/')

@login_required()
def get_student_info(request):
    
    user = request.user
    category = request.GET.get('category')
    studentID = request.GET.get('studentID')
    studentID2 = request.GET.get('studentID2')
    comment = request.GET.get('comment')
    cartoon = request.GET.get('cartoon')
    print(user)
    data = dict()
    data['category'] = category

    # Get student ID's
    freeFieldCategories = ['CompuMaster', 'CompuAdoptado', 'CompuTeam']
    if category not in freeFieldCategories:
        studentID = get_student_id(studentID)

    # Student not found
    if studentID is None:
        data['not_found'] = True
        data['nominate'] = False
        data['already_nominated'] = False
        return HttpResponse(json.dumps(data))

    if studentID2 is not None:
        studentID2 = get_student_id(studentID2)
        if studentID2 is None:
            data['not_found_2'] = True
            data['nominate'] = False
            data['already_nominated'] = False
            return HttpResponse(json.dumps(data))

    # Check if not repeating nomination
    if already_nominated(user, category, studentID, studentID2):
        print(studentID)
        print(studentID2)
        data['already_nominated'] = True
        data['nominate'] = False
        data['nom_id'], data['comment'] = get_nomination_info(user, category, studentID, studentID2)
        
        if category not in freeFieldCategories:
            data['nominee_entity'] = Student.objects.filter(student_id = studentID ).first().person.entity.pk
        else:
            data['nominee_entity'] = studentID

        if category not in freeFieldCategories:
            data['carnet'] = studentID
        else:
            data['carnet'] = ""
        
        data['carnet2']  = studentID2
        data['comment']  = comment
        
        if category == 'CompuCartoon':
            data['cartoon']  = get_cartoon(user, studentID)
        
        if studentID2 is not None:
            data['nomineeOpt_entity'] = Student.objects.filter(student_id = studentID2).first().person.entity.pk

    # Then prepre for nomination
    else:
        # Get nomination info (user, category, studentID, studentID2, comment)
        data['nominate'] = True
        data['already_nominated'] = False
        data['comment']  = comment
        
        if category not in freeFieldCategories:
            data['carnet'] = studentID
        else:
            data['carnet'] = ""

        data['carnet2']  = studentID2
        data['cartoon']  = cartoon

    return HttpResponse(json.dumps(data))


@login_required()
def delete_nomination(request):

    user = request.user
    category = request.GET.get('category')
    studentID = request.GET.get('studentID')
    studentID2 = request.GET.get('studentID2')

    # Get student ID's
    freeFieldCategories = ['CompuMaster', 'CompuAdoptado', 'CompuTeam']
    if category not in freeFieldCategories:
        studentID = get_student_id(studentID)

    if studentID2 is not None:
        studentID2 = get_student_id(studentID2)

    delete_nomination_db(user, category, studentID, studentID2)

    data = dict()

    freeFieldCategories = ['CompuMaster', 'CompuAdoptado', 'CompuTeam']
    if category not in freeFieldCategories:
        data['nominee_entity'] = Student.objects.filter(student_id = studentID ).first().person.entity.pk
        
        if studentID2 is not None:
            data['nomineeOpt_entity'] = Student.objects.filter(student_id = studentID2).first().person.entity.pk
        else:
            data['nomineeOpt_entity'] = None

    else:
        data['nominee_entity'] = studentID
        data['nomineeOpt_entity'] = None		

    return HttpResponse(json.dumps(data))

@login_required()
def make_nomination(request):

    if request.method == "POST":

        user = request.user
        category = request.POST.get('category')
        studentID = request.POST.get('studentID')
        studentID2 = request.POST.get('studentID2')
        comment = request.POST.get('comment')
        cartoon = request.POST.get('cartoon')
        
        if not already_nominated(user, category, get_student_id(studentID), get_student_id(studentID2)):
            make_nomination_db(user, category, studentID, studentID2, comment, cartoon)
    
        data = dict()

        freeFieldCategories = ['CompuMaster', 'CompuAdoptado', 'CompuTeam']
        if category in freeFieldCategories:
            data['nominee_entity'] = studentID
            data['carnet'] = None
            data['comment'] = comment
            data['cartoon'] = None
            data['nomineeOpt_entity'] = None
            data['carnet2'] = None

        else:
            data['nominee_entity'] = Student.objects.filter(student_id = get_student_id(studentID) ).first().person.entity.pk
            data['carnet'] = get_student_id(studentID)
            data['comment'] = comment
            data['cartoon'] = cartoon
    
            if studentID2 is not None:
                data['nomineeOpt_entity'] = Student.objects.filter(student_id = get_student_id(studentID2) ).first().person.entity.pk
                data['carnet2'] = get_student_id(studentID2)
            else:
                data['nomineeOpt_entity'] = None
                data['carnet2'] = None

voting/templates/voting/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Compushow 2018</title>
		<!-- Website icon -->
		<!--<link rel="icon" href="">-->
		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="{% static 'voting/css/bootstrap.min.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">
		<link rel="icon" href="{% static 'voting/images/favicon.png' %}">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'voting/css/base.css' %}"/>
		{% block css %}{% endblock css %}
	</head>

	{% block bodydiv %}
	<body>
	{% endblock bodydiv %}

		<!-- Navigation bar -->
		{% block navbar %}
			<nav id="main-navbar" class="navbar navbar-default navbar-static-top">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="{% url 'voting:index' %}"><span id="nav-compu-title">CompuShow</span> 2018</a>
					</div>
					<div id="navbar" class="navbar-collapse collapse">
						<ul id="navbar-left" class="nav navbar-nav">
							<li class="main-navbar-element {% if home %}actived{% endif %}">
								<a href="{% url 'voting:index' %}">PRINCIPAL</a>
							</li>
							<li class="main-navbar-element {% if nominate %}actived{% endif %} {% if enable_voting %}disabled{% endif %}">
								<a {% if not enable_voting %}href="{% url 'voting:nominate' %}"{% endif %}>NOMINACIONES</a>
							</li>
							<li class="main-navbar-element {% if voting %}actived{% endif %} {% if not enable_voting %}disabled{% endif %}">
								<a {% if enable_voting %}href="{% url 'voting:vote' %}"{% endif %}>VOTACIONES</a>
							</li>
							<form class="navbar-form navbar-left main-navbar-element" action="/view_profile/">
								<div class="input-group search-bar-group">

									<input list="search-bar" name="search-bar" type="text" class="form-control" placeholder="Buscar personas"/>

									<datalist id="search-bar">
    									{% for student in students %}
    										<option value="{{ student.person__name }} {{ student.person__surname }}"></option>
    									{% endfor %}
    								</datalist>

									<div class="input-group-btn">
										<button class="btn btn-default" type="submit">
											<i class="glyphicon glyphicon-search"></i>
										</button>
									</div>



								</div>
							</form>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="dropdown main-navbar-element {% if profile %}actived{% endif %}">
								<a href="#myprofile" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
									<span id="profilename">{{ request.user.first_name | upper }}</span>
									<span style="display:inline-block; width:30px;"></span>
								</a>
								<ul class="dropdown-menu main-navbar-dropdrown">
									<li id="change-pswd"><a data-toggle="modal" data-target="#pswdModal" href="#">Cambiar contraseña</a></li>
									<li class="divider"></li>
									<li><a data-toggle="modal" data-target="#logOutModal" href="#">Cerrar sesión</a></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		{% endblock navbar %}

		<div class="container-fluid">
			{% block body %}
			{% endblock body %}
		</div>

		{% block footer %}
			<footer class="footer">
				<div class="container">
					<p class="text-muted center-align">CEIC USB 2017 - 2018. CDN PATROCINADO POR DARIEN TECHNOLOGY.</p>
				</div>
			</footer>
		{% endblock footer %}

		<!-- Change Password Modal (pop up window) -->
		<div id="pswdModal" class="modal fade" role="dialog">
			<div class="modal-dialog">

				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title text-center">Cambio de contraseña</h4>
					</div>
					<div class="modal-body text-center">
						<form name="ch-pswd-form" class="nominate-form" action="/">

							<label class="ch-pswd-text-1">Nueva contraseña:</label>
							<div id="pswd-group-1" class="input-group">
								<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
								<input id="ch-pswd-1" type="password" class="form-control" name="ch-pswd-1" placeholder="Contraseña">
							</div>

							<label class="ch-pswd-text-2">Repita nueva contraseña:</label>
							<div id="pswd-group-2" class="input-group">
								<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
								<input id="ch-pswd-2" type="password" class="form-control" name="ch-pswd-2" placeholder="Contraseña">
							</div>

						</form>

					</div>
					<div class="modal-footer">
						{% csrf_token %}
						<button type="button" id="ch-pswd-btn" class="btn btn-warning btn-block">
							Cambiar
						</button>

					</div>
				</div>
			</div>
		</div>

		<!-- Successful Update Password Modal (pop up window) -->
		<div id="successfulUpdPswdModal" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-body text-center">
						<p class="h1">¡Cambio de contraseña <span class='text-success'>exitoso</span>!</p>
					</div>
					<div class="modal-footer">
						<form action="{% url 'voting:log_in' %}" >
							<input type="submit" class="btn btn-success btn-block" value="Continuar"/>
						</form>
					</div>
				</div>
			</div>
		</div>

		<!-- Logout Modal (pop up window) -->
		<div id="logOutModal" class="modal fade" role="dialog">
			<div class="modal-dialog">

				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title text-center">Hasta luego, {{ request.user.first_name }}</h4>
					</div>
					<div class="modal-body text-center">
						<p>¿Estás seguro de que deseas cerrar sesión?</p>
					</div>
					<div class="modal-footer">
						<form action="{% url 'voting:log_out' %}" >
							<input type="submit" class="btn btn-danger btn-block" value="Sí, quiero salir."/>
						</form>
					</div>
				</div>
			</div>
		</div>

		<!-- JQuery -->
		<script src="{% static 'voting/js/jquery.min.js' %}"></script>
		<!-- Bootstrap core JavaScript -->
		<script src="{% static 'voting/js/boostrap.min.js' %}"></script>
		<!-- Base script -->
		<script src="{% static 'voting/js/base.js' %}"></script>
		{% block javascript %}{% endblock javascript %}
	</body>
</html>

voting/templates/voting/index.html
{% extends 'voting/base.html' %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'voting/css/index.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'voting/css/base.css' %}"/>
{% endblock css %}

{% block body %}
	

	<div class="container">

		{% if not enable_voting %}

		 	<div class="main-content">
				<div class="row">
					<div class="col-xs-12 col-md-8 presentation">
						<h1><strong>¿Se te hace familiar este paisaje?</strong></h1>
						<div class="main-text">
							<p>¡Ya estamos cerca de comenzar el espectáculo!
								Solo falta que tú escojas los performers que quieres que te traigamos.</p>
						</div>
						<div>
							<p class="main-text">Las nominaciones estarán abiertas desde el martes 12 de junio al martes 19 de junio.</p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="text-center" style="margin-bottom: 50px;">
						<form action="{% url 'voting:nominate' %}">
							<input type="submit" id="goto-nomination-btn" class="btn btn-info" value="Nominar">
						</form>
					</div>
				</div>
			</div>

		{% endif %}

		{% if enable_voting %}

			<div class="main-content" style="padding-top: 5%;">
				<div class="row">
					<div class="col-xs-8 presentation">
						<h3 class="title"><strong>
							<span class="title-head">Ya todo está casi listo para arrancar el espectáculo.</span>
						</strong></h3>
						<div class="title-body info-text">
							<p>Gracias a ti contaremos con la participación de los mejores artistas y las celebridades mas famosas,
									¿te lo vas a perder?
									¡No olvides vestirte a la altura de ellos, te esperamos en el CompuShow 2018!</p>
						</div>
						<div class="period-info info-text">
							<p>El período de votaciones permanecerá
								abierto desde el domingo 24 al miércoles 27 de junio (Semana 10).</p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="text-center">
						<form action="{% url 'voting:vote' %}">
							<input type="submit" id="goto-nomination-btn" class="btn btn-info" value="Votar">
						</form>
					</div>
				</div>
			</div>

		{% endif %}


	</div>

{% endblock body %}

voting/templates/voting/login.html
{% extends 'voting/base.html' %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'voting/css/login.css' %}"/>
{% endblock css %}

{% block navbar %}{% endblock navbar %}

{% block body %}


	<div class="">
		<div class="row">
			<div class="col-md-8 hidden-xs hidden-sm" id="left-side-login"></div>
			<div class="col-md-4 col-xs-12" id="form-login-container">
				<h1 class="visible-xs-block text-center form-heading" style="color: white;" >Compushow <br><span>2017-2018</span></h1>
                <h2 style="text-align: center;color: white">Inicio de Sesión</h2>
				<form class="form-login" action="{% url 'voting:log_in' %}" method="post">
					{% csrf_token %}
					<div class="form-id-field">
						{{ form.student_id }}
					</div>
					<div>
						{{ form.password }}
					</div>

					{% if invalid or form.student_id.errors %}
						<div class="alert alert-danger alert-dismissable fade in invalid">
							{% if form.student_id.errors %}<strong>Error:</strong> Carnet inválido. e.g. 12-34567{% endif %}
							{% if notfound %}<strong>Error:</strong> Carnet no encontrado.{% endif %}
							{% if notcs %}<strong>Alerta:</strong> No está registrado como estudiante de computación.{% endif %}
							{% if invalidpasswd %}<strong>Alerta:</strong> Constraseña inválida.{% endif %}
						</div>
					{% endif %}

					<button id="loginbtn" class="btn btn-lg btn-info btn-block" type="submit">Ingresar</button>

					{% if not_activated %}
						<div class="alert alert-info alert-dismissable fade in invalid">
							<strong>Información:</strong> Se ha enviado un correo de activación de cuenta a su correo institucional.
						</div>
					{% endif %}

					{% if activation_success %}
						<div class="alert alert-success alert-dismissable fade in invalid">
							Gracias por confirmar el correo electrónico. ¡Ya puedes acceder a tu cuenta!
						</div>
					{% endif %}

				</form>
			</div>
		</div>

	</div>


{% endblock body %}

voting/templates/voting/registration_success.html
{% extends 'voting/base.html' %}

{% block css %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'voting/css/login.css' %}"/>
{% endblock css %}

{% block navbar %}{% endblock navbar %}

{% block body %}


	<div class="container">

		<form class="form-login" style="padding:30px;">
		
			{% if invalid %}
				<div class="alert alert-danger alert-dismissable fade in invalid text-center" style="padding:10px;">
					<strong>Error:</strong> Link de activación inválido.
				</div>

			{% else %}
				<div class="alert alert-success alert-dismissable fade in invalid text-center" style="padding:10px;">
					<p>Gracias por confirmar el correo electrónico.</p>
					<strong><p>¡Ya puedes acceder a tu cuenta!</p></strong>
				</div>
			{% endif %}

		</form>

	</div>


{% endblock body %}